version: '2.1'
services:
  mysql:
    image: cadec2019/mysql
    build:
      context: mysql
    ports:
     - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: customer
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=mysql --password=secret --execute \"SHOW DATABASES;\""]
      interval: 10s
      timeout: 5s
      retries: 5
  order:
    image: cadec2019/order:initial
    ports:
     - 8080:8080
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  invoicing:
    image: cadec2019/invoicing:initial
    ports:
     - 8081:8080
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  shipping:
    image: cadec2019/shipping:initial
    ports:
     - 8082:8080
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  customer:
    image: cadec2019/customer:initial
    ports:
     - 8083:8080
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
