server:
  port: 8080
logging:
  pattern:
    console: "%date{HH:mm:ss.SSS} %msg%n"
  level:
    root: WARN
    se:
      callista:
        cadec:
          eda: INFO
spring:
  main:
    banner-mode: "OFF"  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:localhost}:9092
kafka:
  topic:
    orders: orders
