server:
  port: 8081
logging:
  pattern:
    console: "%date{HH:mm:ss.SSS} %msg%n"
  level:
    root: WARN
    se:
      callista:
        cadec:
          eda: INFO
spring:
  main:
    banner-mode: "OFF"  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:localhost}:9092
    consumer:
      auto-offset-reset: earliest
      group-id: invoicing
  data:
    redis:
      repositories:
        enabled: true
      host: ${DOCKER_HOST_IP:localhost}
      port: 6379
kafka:
  topic:
    orders: orders
    customers: customers
